# Generated by Django 3.0 on 2019-12-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento', '0004_auto_20191206_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='tipolancamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipolancamento_fk', to='lancamento.TipoLancamento'),
        ),
    ]
